var object = 'laptop';
console.log("Are these scissors? I predict True");
console.log(object == 'scissors');
var colour = 'purple';
console.log("Is the color of box white?");
console.log(colour == 'white');
var vehicle = 'motor-cycle';
console.log("I predict that this is the motor-cycle");
console.log(vehicle == 'motor-cycle');
var day = 'sunday';
console.log("Today is Saturday");
console.log(day == 'Saturday');
var subject = 'zoology';
console.log("She prefers biology over zoology");
console.log(subject == 'biology');
var place = 'curtains';
console.log("I think mom is hiding behind curtains");
console.log(place == 'curtains');
var country = 'South Korea';
console.log("BTS are from South Korea");
console.log(country == 'South Korea');
var religion = 'Islam';
console.log("Islam is a peaceful religion");
console.log(religion == 'Islam');
var taste = 'Chinese';
console.log("She loves Italian food");
console.log(taste == 'Italian');
var father = 'Indian';
console.log("I think your father belongs to India");
console.log(father == 'Indian');
